steps:
  - name: 'maven:3-jdk-8'
    entrypoint: mvn
    args: ["package", "-Dmaven.test.skip=true"]
  - name: 'gcr.io/cloud-builders/docker'
    args: ["build", "-t", "gcr.io/$PROJECT_ID/orksproject", "--build-arg=JAR_FILE=target/api-0.0.1-SNAPSHOT.jar", "."]

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'gcr.io/$PROJECT_ID/orksproject' ]
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: [ 'run', 'deploy', 'orksproject', '--image', 'gcr.io/$PROJECT_ID/orksproject', '--region', 'asia-southeast1', '--platform', 'managed', '--allow-unauthenticated' ]
images: ["gcr.io/$PROJECT_ID/orksproject"]